In [1]:
print("meow")

meow

In [7]:
import pandas as pd

df = pd.read_excel('~/Downloads/Fall Battle 2021.xlsx', sheet_name="Master Roster")

In [36]:
teams = [
    {"id": 1, "name": "Elijah"},
    {"id": 2, "name": "Ka'eo"},
    {"id": 3, "name": "Kulani "},
    {"id": 4, "name": "Oliver"},
    {"id": 5, "name": "BiggDave "},
    {"id": 6, "name": "David G. "},
    {"id": 7, "name": "Genny"},
    {"id": 8, "name": "Russell "},
]

delete_names = ["TJ Moen", "Mark Sells"]

In [39]:
compiled = []
id = 1
for t in teams:
    athletes = df[t['name']].dropna().to_list()
    for a in athletes:
        
        skip = False
        for d in delete_names:
            if d in a:
                skip = True
                continue
        if skip:
            continue

        compiled.append((id, t['id'], a))
        id += 1
compiled

[(1, 1, 'Jodie Goldberg'),
 (2, 1, 'Jennifer Hensley'),
 (3, 1, 'Mike Goldberg'),
 (4, 1, 'Mike Hudson'),
 (5, 1, 'Aaron Kerr'),
 (6, 1, 'Leslie Powell'),
 (7, 1, 'Nissa Van Etten'),
 (8, 1, 'Greg Van Etten'),
 (9, 1, 'Melinda Grebe'),
 (10, 1, 'Meaw Medich'),
 (11, 1, 'Jay DeFoore'),
 (12, 1, 'Jack Blake'),
 (13, 1, 'Kiffin Klos'),
 (14, 1, 'Corey Jahn'),
 (15, 1, 'Sylvia Alexander'),
 (16, 1, 'Breyden Bales'),
 (17, 1, 'Anna Kraft '),
 (18, 1, 'Seth Michael'),
 (19, 1, 'Sam Preston'),
 (20, 1, 'Ashen (Tillman PT)'),
 (21, 1, 'Katherine Hernandez'),
 (22, 1, 'Cara Wilkinson'),
 (23, 1, 'Keith Linenberger '),
 (24, 1, 'Lewis Martinez'),
 (25, 2, 'Molly Lewis'),
 (26, 2, 'Julie Clarke'),
 (27, 2, 'Dan Clarke'),
 (28, 2, 'Thomas Young'),
 (29, 2, 'David Litzau'),
 (30, 2, 'Chris Leonard'),
 (31, 2, 'Laura Mills'),
 (32, 2, 'Heather Van Stavern'),
 (33, 2, 'Jasmine DeFoore'),
 (34, 2, 'Lyndsey Williams'),
 (35, 2, 'Duncan Boggs'),
 (36, 2, 'Addison Cox'),
 (37, 2, 'Deborah Kogler'),
 (38, 2, 'Jim Peterson'),
 (39, 2, 'Terry Schertz'),
 (40, 2, 'Andrew Delbridge'),
 (41, 2, 'Richard McDonell'),
 (42, 2, 'Adam Kogler'),
 (43, 2, 'Wes Nickerson'),
 (44, 2, 'Daniel Hamm'),
 (45, 2, 'Salma Korrub'),
 (46, 2, 'Lino Kaethner'),
 (47, 2, 'Tad Hensley'),
 (48, 2, 'Oliver Preston'),
 (49, 2, 'Quin Hendricks'),
 (50, 3, 'Rose Subiono'),
 (51, 3, 'Vicki Sanchez'),
 (52, 3, 'Timothy Preston'),
 (53, 3, 'Elizabeth Preston'),
 (54, 3, 'Samantha Allen'),
 (55, 3, 'Pamela Ackert'),
 (56, 3, 'Savanna Rees'),
 (57, 3, 'Hanieh Esfahani'),
 (58, 3, 'Kyanoosh Shafaei'),
 (59, 3, 'Steven Hobson'),
 (60, 3, 'Jenn Moxon'),
 (61, 3, 'Ben Hahn'),
 (62, 3, 'Chelsea Rivas'),
 (63, 3, 'Rafael Rivas'),
 (64, 3, 'John Krueger'),
 (65, 3, 'Cristopher Erickson'),
 (66, 3, 'Marta Abrams'),
 (67, 3, 'Melissa Moore'),
 (68, 3, 'Veneranda Reyes'),
 (69, 3, 'Landon Debello'),
 (70, 3, 'John Howard'),
 (71, 3, 'Kristine Branstetter'),
 (72, 4, 'Morgan Daleo'),
 (73, 4, 'Colin Moore'),
 (74, 4, 'Heather Fox'),
 (75, 4, 'LaVonne Lorg'),
 (76, 4, 'Anna Bales'),
 (77, 4, 'Megan Lowder'),
 (78, 4, 'Pete Papaiaonnau'),
 (79, 4, 'Blake Milchuck '),
 (80, 4, 'Amanda Gosney '),
 (81, 4, 'Lorra Dailey '),
 (82, 4, 'Stacy Himba'),
 (83, 4, 'Jake Flores'),
 (84, 4, 'Rich Williams'),
 (85, 4, 'Marisol Sandoval'),
 (86, 4, 'Josh Orellana '),
 (87, 4, 'Mel Mattsen '),
 (88, 4, 'Geoff Korrub'),
 (89, 4, 'Suzette Hendrick'),
 (90, 4, 'Cole Hendrick'),
 (91, 4, 'Don Wilson '),
 (92, 4, 'Margaret Wilson'),
 (93, 4, 'Margarite'),
 (94, 4, 'Brad Van Stavern'),
 (95, 4, 'Hatyden Hoffman'),
 (96, 4, 'Zach Ortegon'),
 (97, 5, 'Karen Trenk'),
 (98, 5, 'Kimber Kurachi'),
 (99, 5, 'Sean Kenealy'),
 (100, 5, 'Amy Allen'),
 (101, 5, 'Dede Lakey'),
 (102, 5, 'Erika Johnson'),
 (103, 5, 'Kevin Mann'),
 (104, 5, 'Holly Hillis'),
 (105, 5, 'Kevin Fox'),
 (106, 5, 'Kyle Meece'),
 (107, 5, 'Sheila Hickerson'),
 (108, 5, 'Bonnie Caudill'),
 (109, 5, 'Kristen Munoz'),
 (110, 5, 'Lauren Pettineo'),
 (111, 5, 'Greg Meador'),
 (112, 5, 'Wade Aubin'),
 (113, 5, 'Anne Michel'),
 (114, 5, 'Kim Loftin'),
 (115, 6, 'Anna Gilmore'),
 (116, 6, 'Lisa Vasile'),
 (117, 6, 'Calvin Ong'),
 (118, 6, 'Aimie Black'),
 (119, 6, 'Gerald Talton'),
 (120, 6, 'Carla Khalsa'),
 (121, 6, 'Luis Rustrian '),
 (122, 6, 'Matthew Whittington'),
 (123, 6, 'K Leigh Forell'),
 (124, 6, 'Shantel king'),
 (125, 6, 'Trent Thompson'),
 (126, 6, 'Bill Cyree'),
 (127, 6, 'Paul Fenrich'),
 (128, 6, 'Trevor Hance'),
 (129, 6, 'Erin Crews'),
 (130, 6, '*Nikki Torrez'),
 (131, 6, 'Aaron Medina'),
 (132, 6, 'Chelsea Hanson'),
 (133, 6, 'Lameace Salman'),
 (134, 7, 'Christi Hoover'),
 (135, 7, 'Marcia Vandover'),
 (136, 7, 'Jeremy Brown'),
 (137, 7, 'James Reese'),
 (138, 7, 'Robert Ayala'),
 (139, 7, 'Mandy Reese'),
 (140, 7, 'Silvia Galarza'),
 (141, 7, 'Josh Rundall'),
 (142, 7, 'Lydia Lai'),
 (143, 7, 'Summer Strum'),
 (144, 7, 'Mia Mann'),
 (145, 7, 'Adam Cox'),
 (146, 7, 'Shanel Fortney '),
 (147, 7, 'Corrina Mayor'),
 (148, 7, 'Brian Gregory'),
 (149, 7, 'Aaron Crews'),
 (150, 7, 'Dan Castro'),
 (151, 8, 'Mari Mays'),
 (152, 8, 'Chad Mellon'),
 (153, 8, 'Joye Hooper'),
 (154, 8, 'Alice Hulsey'),
 (155, 8, 'Glen Pratt'),
 (156, 8, 'Carrie Weir'),
 (157, 8, 'Alexis Russell'),
 (158, 8, 'Tami Stromberg'),
 (159, 8, 'Karl Boettcher'),
 (160, 8, 'Shawn Randels'),
 (161, 8, 'Kelli Kurachi'),
 (162, 8, 'Brad Floyd'),
 (163, 8, 'Gomti Mehta'),
 (164, 8, 'Phil Fuerstner'),
 (165, 8, 'Juliane Fuerstner'),
 (166, 8, 'Sijith Ganga'),
 (167, 8, 'Eric Dehoux'),
 (168, 8, 'Lindsay Gregory'),
 (169, 8, 'Aaron Merritt')]

In [38]:
"Mark Sells" in "Mark Sells*\nHe went on hold for November"

True